version: "3.9"

services:
  web:
    build: .
    command: sh -c "python manage.py migrate
      && gunicorn core.wsgi:application --forwarded-allow-ips="*" --timeout=300 --workers=5 --bind 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "15253:8000"